### ISSUE TITLE
Unable to get tmap installed on Jupyter Notebook via Binder & Docker

### ISSUE THREAD

**Issue by RAJohansen** [RAJohansen/BindeR#1]
Need to investigate tmap and tmap dependencies. They are not loading correctly in jupyter notebook although it and its dependencies seem to install correctly in binder. 

Any idea @nowosad

**Comment by Nowosad** [comment]
https://github.com/mtennekes/tmap/issues/288

**Comment by RAJohansen** [comment]
Raster and leaflet work, but sf and tmap still do not???

**Comment by RAJohansen** [comment]
Adding a dockerfile from rocker (https://github.com/rocker-org/binder) solved the dependency problem.

**Example of dockerfile**
```
FROM rocker/binder
## Copies your repo files into the Docker Container
USER root
COPY . ${HOME}
RUN chown -R ${NB_USER} ${HOME}

## Become normal user again
USER ${NB_USER}

## Run an install.R script, if it exists.
RUN if [ -f install.R ]; then R --quiet -f install.R; fi
```
